### ISSUE TITLE
Author Profile Pic

### ISSUE THREAD

**Issue by carolynvs** [WriteSpeakCode/accomplishments#1]
It would be nice to show an author profile pic next to an accomplishment. While gravatar seems like a good fit, using it would require that we don't rely upon GitHub to generate our site when we push, and instead we would have to generate it locally and push it (or have a CI build). 

One idea is to just allow people to provide a link to their gravatar, or some other profile pic.

``` yaml

---
title: Foobar
author: Someone Awesome
author-image: ﻿﻿﻿﻿https://secure.gravatar.com/avatar/8b96f8872eb3f398809daf017ee3a8ab

---
```
